export const types = {
  START_LOGIN: "START_LOGIN",
  AUTH_USER: "AUTH_USER",
  SUCCES_LOGIN: "SUCCES_LOGIN",
  GET_USER_INFO: "GET_USER_INFO",
  LOGOUT: "LOGOUT",
  START_REQUEST: "START_REQUEST",
  SUCCES_REQUEST: "SUCCES_REQUEST",
};
